name: MOZAIC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25636846013367176
title: MOZAIC Private Holding Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b4c5e'
    - '#3e6b90'
    - '#f05a69'
    - '#748ba9'
  brandStrength: 0.674174135318026
  lightness: 0.06692712963558733
  saturation: 0.10940189403481781
  rhythmicContrast: 0.906874920707196
purpose: []
